import { test, expect } from '@playwright/test';
import path from 'path';


test('tramites - Solicitud', async ({ page }) => {
  const doc_test = path.join(__dirname, 'docs_test/Documento1.pdf');
  await page.goto('https://abt.bits.bo/auth/login');
  await page.getByRole('button', { name: 'INGRESAR COMO AGENTE AUXILIAR' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).fill('jpvel');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('123456789');
  await page.getByRole('button', { name: 'INICIAR SESIÓN' }).click();
  await page.getByRole('button', { name: '+' }).click();
  await page.getByRole('link', { name: 'Derecho Agrario Derecho' }).click();
  await page.locator('app-instrument-card').filter({ hasText: 'POP Plan de Ordenamiento' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Propiedad Privada' }).click();
  await page.getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('DDSC - Santa Cruz').click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('combobox', { name: 'Razón Social' }).click();
  await page.locator('form button').nth(3).click();
  await page.getByText('Parapeti').click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test);
  await page.locator('input[type="file"]').nth(2).setInputFiles(doc_test);
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test);
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test);
  await page.locator('input[type="file"]').nth(2).setInputFiles(doc_test);
  await page.locator('input[type="file"]').nth(3).setInputFiles(doc_test);
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test);
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test) ;
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('input[type="file"]').nth(1).setInputFiles(doc_test) ;
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByText('¡Felicidades! Ha completado el formulario de manera exitosa. Le notificaremos a').click();
});