import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://abt.bits.bo/auth/login');
  await page.getByRole('button', { name: 'INGRESAR COMO AGENTE AUXILIAR' }).click();
  await page.getByRole('link', { name: 'Solicitud de Credenciales' }).click();
  await page.getByRole('button', { name: 'persona_natural Persona' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('v01jbhr3cg@jxpomup.com');
  await page.getByRole('textbox', { name: 'Nombre de usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de usuario' }).fill('jpvel');
  await page.getByRole('textbox', { name: 'Nombres' }).click();
  await page.getByRole('textbox', { name: 'Nombres' }).fill('juan');
  await page.getByRole('textbox', { name: 'Primer Apellido' }).click();
  await page.getByRole('textbox', { name: 'Primer Apellido' }).fill('velano');
  await page.getByRole('textbox', { name: 'Segundo Apellido' }).click();
  await page.getByRole('textbox', { name: 'Segundo Apellido' }).fill('velano');
  await page.getByRole('textbox', { name: '99999999' }).click();
  await page.getByRole('textbox', { name: '99999999' }).fill('77777777');
  await page.getByRole('textbox', { name: 'Nro. de CI' }).click();
  await page.getByRole('textbox', { name: 'Nro. de CI' }).fill('2631231');
  await page.getByRole('combobox', { name: 'Expedido' }).click();
  await page.getByText('La Paz').click();
  await page.locator('span').filter({ hasText: 'Seleccionar' }).first().click();
  await page.locator('span').filter({ hasText: 'Seleccionar' }).first().setInputFiles('0a9c47a6502f6119888b77fa232d4598.jpg');
  await page.getByRole('combobox', { name: 'Nacionalidad' }).click();
  await page.getByText('BO-Bolivia').click();
  await page.getByRole('textbox', { name: 'Dirección domiciliaria' }).click();
  await page.getByRole('textbox', { name: 'Dirección domiciliaria' }).fill('Ceja');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: '+ Añadir' }).click();
  await page.getByRole('combobox', { name: 'Seleccionar' }).first().click();
  await page.getByRole('option', { name: 'Ingeniero Forestal' }).click();
  await page.getByLabel('Seleccionar').click();
  await page.getByText('Licenciatura').click();
  await page.getByRole('textbox', { name: 'Nº Título' }).click();
  await page.getByRole('textbox', { name: 'Nº Título' }).fill('123123123');
  await page.getByRole('combobox', { name: 'Seleccionar' }).click();
  await page.getByText('24').click();
  await page.getByRole('textbox', { name: 'Institución que emite el tí' }).click();
  await page.getByRole('textbox', { name: 'Institución que emite el tí' }).fill('UMSA');
  await page.getByRole('cell', { name: 'true Seleccionar 100MB Max.' }).locator('span').first().click();
  await page.getByRole('cell', { name: 'true Seleccionar 100MB Max.' }).locator('span').first().setInputFiles('0a9c47a6502f6119888b77fa232d4598.jpg');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('row', { name: 'Copia de su Título' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Copia de su Título' }).locator('span').first().click();
  await page.getByRole('row', { name: 'Copia de su Título' }).locator('span').first().setInputFiles('0a9c47a6502f6119888b77fa232d4598.jpg');
  await page.getByRole('row', { name: 'Copia de su Cédula de' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Copia de su Cédula de' }).getByRole('button').first().click();
  await page.getByRole('row', { name: 'Currículum Vitae 100MB Max.' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Currículum Vitae true' }).getByRole('button').first().click();
  await page.getByRole('row', { name: 'Formulario 25 100MB Max.' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Formulario 25 true' }).getByRole('button').first().click();
  await page.getByRole('combobox', { name: 'Seleccionar' }).click();
  await page.locator('#entity_3').click();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('span').filter({ hasText: 'Seleccionar' }).first().click();
  await page.locator('span').filter({ hasText: 'Seleccionar' }).first().setInputFiles('Documento1.pdf');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('button', { name: 'Enviar' }).click();
  await page.getByLabel('Enviar solicitud').getByRole('button', { name: 'Enviar' }).click();
  await page.getByRole('button', { name: 'Ir a Iniciar Sesión' }).click();
  await page.getByText('Iniciar Sesión').click();
});
